---
sudo: false
dist: trusty
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort
addons:
  apt:
    packages:
      - libssl-dev
      - libxml2-dev
      - libxmlsec1
      - libxmlsec1-dev
      - libxmlsec1-openssl
      - libxslt1-dev
      - pkg-config
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOXENV
after_success:
  - coveralls
