---
sudo: required
dist: trusty
language: python
services:
  - docker
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort
before_install:
- docker build -t initios/aeatws .
- docker ps -a
- docker run initios/aeatws -v ./:/app -c "tox -e $TOXENV"
script:
  - tox -e $TOXENV
after_success:
  - coveralls
